server:
  port: 1133

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_mall?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
#  mapper-locations: classpath:com/iyqrj/starmall/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.iyqrj.starmall.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

password.salt:
  geelysdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,